---
- name: update apt cache
  become: yes
  apt:
    update_cache: yes

- name: install aptitude
  apt: 
    pkg: aptitude
  become: yes
  
- name: apt upgrade
  become: yes
  apt:
    upgrade: full

- name: install packages required for shopware.dev setup
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - sudo
    - git
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - software-properties-common
    - php
    - libapache2-mod-php
    - php-cli
    - mysql-server
    - python-mysqldb
    - composer
    - nodejs
    - npm
    - chromium-browser
    - default-jre-headless
    - docker.io
    - docker-compose

- name: install php extensions
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - php-gd 
    - php-intl 
    - php-iconv 
    - php-mbstring 
    - php-mysql 
    - php-xml 
    - php-zip 
    - php-json
    - php-curl

- name: add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes

- name: install apache2
  become: yes
  apt:
    pkg: apache2
    state: latest
