---
- name: install nginx
  become: yes
  apt:
    name: nginx
    state: present

- name: remove default vhost
  become: yes
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: setup vhost
  become: yes
  template:
    src: vhost-http.j2
    dest: "/etc/nginx/sites-enabled/{{ proxy_hostname }}"
  when: not proxy_ssl
  notify: restart-nginx

- name: configure ssl
  become: yes
  block:
    - name: setup certificate
      import_tasks: ssl.yml
    - name: setup secure vhost
      template:
        src: vhost-https.j2
        dest: "/etc/nginx/sites-enabled/{{ proxy_hostname }}"
      notify: restart-nginx
  when: proxy_ssl
